All: checkIfCharacter findLargestValue printGrades

checkIfCharacter: checkIfCharacter.s
	gcc $@.s -g -o $@
	./checkIfCharacter       
findLargestValue: findLargestValue.s
	gcc $@.s -g -o $@
	./findLargestValue
printGrades: printGrades.s
	gcc $@.s -g -o $@
	./printGrades
