All: checkIfCharacter checkIfCharacterNotLogical findLargestValue printGrades

checkIfCharacter: checkIfCharacter.s
	gcc $@.s -g -o $@
	./checkIfCharacter       
checkIfCharacterNotLogical: checkIfCharacter.s
	gcc $@.s -g -o $@
	./checkIfCharacterNotLogical
findLargestValue: findLargestValue.s
	gcc $@.s -g -o $@
	./findLargestValue
printGrades: printGrades.s
	gcc $@.s -g -o $@
	./printGrades
